name: ci

on:
  push:
    branches: [main]
  pull_request:

jobs:
  rust:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v2
        with:
          version: 0.15.2
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.96.1
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
      - run: cargo fmt --all -- --check
      - run: cargo clippy --locked --all-targets -- -D warnings
      - run: cargo test --locked -- --test-threads=1
